nelmio_api_doc:
    documentation:
        info:
            title: My API
            description: API documentation
            version: 1.0.0
    areas:
        default:
            path_patterns:
                - ^/v1/api
