# config/services.yaml

services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true 
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Security\BearerTokenAuthenticator:
        arguments:
            $userRepository: '@App\Repository\UserRepository'
        tags: ['security.authenticator']
        
    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    App\UserEventSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }
